version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: always
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
